### ISSUE TITLE
[Bug]: when using >=2 powergrid tables on one page, the editOnClick throws an error

### ISSUE THREAD

**Issue by pieteroskam** [Power-Components/livewire-powergrid#1075]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.8.6

### Laravel

10.16.0

### Livewire

2.12.3 

### Theme

Bootstrap

### Describe the bug.

On a Golf round overview page I load a ScoreTable and a Shots table using powergrid

When using the editOnClick for the score table, it also tries to update the $score on the ShotsTable, which is non existent. 

I fixed the issue for now by adding the following code to the ShotsTable

`    public array $score = [];`

It was a quick fix, but still a bug-quick-fix

### To Reproduce...

Make 2 powergridtables
add them to 1 blade file
make a field editable on 1 table
edit table field and hit ent

### Extra information

```markdown
<?php
 //...
```

**Comment by VitorRamosPA** [comment]
I have the same error, when use editOnClick(), the value don't update and when i click to try change again, the vallue that i try update, is there.
Example: Ignore the values don't be equivalent to column value.

Before edit
![image](https://github.com/Power-Components/livewire-powergrid/assets/89878758/b402060b-4cbd-46bb-8870-e8ac41f9ee31)

During edit (ps: have another error because permit click to edit more than one value)
![image](https://github.com/Power-Components/livewire-powergrid/assets/89878758/0db792f1-ee74-4800-8f00-9dbb485f6148)

After click enter:
![image](https://github.com/Power-Components/livewire-powergrid/assets/89878758/d8b18f2f-03a5-4d7c-b89c-38e47c19e9b3)

If i click again at the value:
![image](https://github.com/Power-Components/livewire-powergrid/assets/89878758/e99d4de1-2cf0-4956-a5f0-13d71c1c84f6)

**Comment by luanfreitasdev** [comment]
Hello!. Can you send a video? Are there errors in the console?

**Comment by VitorRamosPA** [comment]
https://youtu.be/-RxOH5lqris

**Comment by VitorRamosPA** [comment]
It was my error, i don't had placed onUpdatedEditable() an my Model had no $fillable with the values

**Comment by luanfreitasdev** [comment]
That might be it, I just tested it here and it's working. The behavior of jumping from one input to another and remaining open is the default behavior until you press Enter or Esc.

https://github.com/Power-Components/livewire-powergrid/assets/33601626/1e979a94-bb46-4d72-a74b-53ba88399ff7

For reference:

https://github.com/Power-Components/powergrid-demo-misc/blob/main/app/Http/Livewire/ValidationTable.php#L54

https://v4.livewire-powergrid.com/table/update-data.html?id=editonclick#editonclick
