### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by jamesRUS52** [Power-Components/livewire-powergrid#271]
Hello.
First of all, thank you for this component. 
I review several like this, but this look more complete then others.
I have some questinons and suggetions for you to improve it.
If some of them more complex I can separate its to single issues.

1. Not working with alpine, bootstrap-select, flickr installed with npm and mix.
I've installed these versions

```
"dependencies": {
        "@popperjs/core": "^2.11.2",
        "alpinejs": "^3.8.1",
        "bootstrap": "^5.1.3",
        "bootstrap-icons": "^1.8.1",
        "bootstrap-select": "^1.14.0-beta2",
        "flatpickr": "^4.6.9",
        "jquery": "^3.6.0"
    }
```
my app.js

```
require('./bootstrap');


window.$ = window.jQuery = require('jquery');

import * as bootstrap from 'bootstrap';
window.bootstrap = require('bootstrap');

import flatpickr from "flatpickr";
import { Russian } from "flatpickr/dist/l10n/ru.js"
import 'flatpickr/dist/flatpickr.min.css'

import Alpine from 'alpinejs'
window.Alpine = Alpine
import './../../vendor/power-components/livewire-powergrid/dist/powergrid'
Alpine.start()

import 'bootstrap-select/dist/js/bootstrap-select'
import 'bootstrap-select/dist/css/bootstrap-select.css'
```

Errors in console browser
```
Uncaught ReferenceError: bootstrap is not defined
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: $ is not defined
```
the errors are gone when comment last two lines.

all urls params in config set to null

2. Multiselect filter lose multiple selected values when component rerendered.
Error occure only if more then one values selected.

3. What is outside filter type? I've tried it but nothing happen. What should I do to move filters from header to another place?

4. InputRange has hardcoded min-width, max-width, it not resize when I change width size for column

5. I think Flickr should have autocomplete attribute to off to avoid overlaping by browser suggestions. May by it happens because filter lose some css properties that avoiding direct input editing when another multiselect filter reset own vales (see the second question)

6. Aggregated total functions (withSum, withCount, withAvg) not supported simple Collection datasource ?
6.1 please add min and max functions
6.2 add those functions to paginated rows too. I would like to see sum on current page and total sum on all pages

7. How to colspan headers and cells? (low priority)
8. Is it possible to make sub total row? e.g. grouping by values on some column (low priority)

9. Deffer render table. 
Is it possible to render table not in mount? I would like create component, but generate data in it later, e.g. event by another livewire component.

10. Component not working inside another livewire component
11. Is it possible to save filters and columns visibility to cookies and restore it by default if it present?
12. send livewire request only when finish date selected in flatpicker (second click). I think first request is unnesasery. Collapse filter after period is selected
13. I cannot align the text in cell, I think justify-content-between should by removed by default (or leave only for clickToCopy) from td>span and add method to set class/style for this span

First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [ ] Yes - I did not find it

Is there an error in the console?
- [ ] Yes - I'll put a screenshot

Powergrid 2.2.4

**Laravel version (exactly)** 
8.79
*

**Livewire version (exactly)**
2.9
*

**AlpineJS:** 
3.8.1
*

**Theme:**
- [ ] Bootstrap - Version:        5

**Comment by luanfreitasdev** [comment]
Hello @jamesRUS52 , Thank you very much for your review, let's get to the main points:

1. It works, take a look at this branch: https://github.com/Power-Components/powergrid-demo/tree/bs5-webpack
  1.1 - Adding a multi-select component to bootstrap5 would be the best way out, as we would no longer rely on the bootstrap-select package. (_feel free to send a PR_)
2. If it is bootstrap and everything is not working with jquery, bootstrap and bootstrap-select will probably cause several errors
3. Not available in bootstrap 5 - https://github.com/Power-Components/livewire-powergrid/issues/96
4. Improvement suggestion - **low priority**
5. Improvement suggestion - **medium priority**
6. _Aggregated total functions (withSum, withCount, withAvg) not supported simple Collection datasource ? (Not for the time being)
6.1 please add min and max functions - (_Improvement suggestion_)
6.2 add those functions to paginated rows too. I would like to see sum on current page and total_ sum on all pages (_Improvement suggestion_)
7. I haven't had this use case yet. 
8. It is not possible, because currently the use is in very specific cases
9. No, but you can control this by placing a variable on the component's mount and setting it to true when a condition occurs.
10. It always worked inside another component, could you send a screenshot and how are you doing? - _question_
11. No, but it's already in the backlog for the future (_feel free to send a PR_)
12. Event is firing when two dates are selected
13. feel free to send a PR (_low priority_)

All items mentioned, if anyone else has this problem in bootstrap 5 feel free to send a PR, anything I'll help.
