### ISSUE TITLE
multiselect filter layout

### ISSUE THREAD

**Issue by jamesRUS52** [Power-Components/livewire-powergrid#321]
Multiselect filter make vertical scrolling of table when number of rows too small (less than height of multiselect items)

![image](https://user-images.githubusercontent.com/39707635/157606697-5b8ead79-a138-4d8d-a114-21a04af99b0f.png)

Do you have any ideas how to fix it?

I tried several ways, but no result

**Comment by luanfreitasdev** [comment]
This is a problem that needs attention. I'll search these days.

**Comment by asosadeq** [comment]
I have the same problem how I can fix it??

**Comment by PH7-Jack** [comment]
@luanfreitasdev 
The problem happens because an absolute div is bigger than the parent div that has the overflow auto, if remove the overflow the absolute div can grow down but will need to refactor your table to have the overflow scroll and the select growing down above the scroller.
Another way to fix it is teleporting the select popover to outside the parent with overflow-auto.


![image](https://user-images.githubusercontent.com/38913462/178147316-ec6a12af-78ed-44b1-900a-aefaf96cac84.png)

**Comment by luanfreitasdev** [comment]
Hi @PH7-Jack !.

Good observation. Do you think there would be a lot of refactoring in the structure of the tables?

**Comment by PH7-Jack** [comment]
@luanfreitasdev I think so because the parent div contains the overflow-auto.
But it's also possible by teleporting the popover to grow outside the table. 
I'll create a POC for it, we can open the popover outside and set the position to be on the select position. (Hack)

**Comment by luanfreitasdev** [comment]
I believe this problem can be closed because it is not possible to do this without using a div. The best solution is to place the selection filter on top of the powergrid component. 
It is currently possible to change the way filters are displayed to 'outside' in the settings.
