### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by gallomaf** [Power-Components/livewire-powergrid#330]
First of all, did you see if your problem has happened to other people before?
- [ x ] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [ x ] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [ x ] No

**Describe the bug**

* I created a PowerGrid from Model. 
* In the model class it's present a field in `$appends = [denominazione]`.
in the Model Class there is the method 

```
    public function getDenominazioneAttribute()
    {
        $denominazione = $this->attributes['ragione_sociale_1'];
        if(isset($this->ragione_sociale_2) && $this->ragione_sociale_2 != ""){
            $denominazione = $this->attributes['ragione_sociale_1'] . " " . $this->attributes['ragione_sociale_2'];
        }
        if(strlen($denominazione) > 30 )
            $denominazione = substr($denominazione, 0, 30) . "...";
        return $denominazione;
    }

```
In PowerGrid I made `addColumn('denominazione')` and 

```
            Column::add()
                ->title('Denominazione')
                ->field('denominazione')
                ->sortable()
                ->searchable()
                ->makeInputText(),
```
but when I try search in this column, I have the error, that the column not exists.

```
select count(*) as aggregate 
from [ordine_cliente] 
left join [gls_spedizione] on [gls_spedizione].[id_ordine] = [ordine_cliente].[id] 
where [ordine_cliente].[stato] = 0 
and [ordine_cliente].[tabella] in (dec_sales_order, multi_ordine) 
and (([denominazione] LIKE %Pina%))
```

There is a way to search with field denominazione like a concat?

thank you

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 

* 9.3.0

**Livewire version (exactly)**

*  3.0

**AlpineJS:** 

*

**Theme:**
- [ ] Tailwind 2.x
- [x ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

I could make a new column in the table like a concat of previous, but is not elegant

**Put part of your code, an html screenshot of the problem element:**

**Comment by dansysanalyst** [comment]
Hi @gallomaf,

Laravel adds the appends attributes after the database is queried. We could say it is a "virtual column".

It is not possible to ask (query) the database using a column that doesn't exist.

For instance, I appended a property called `is_diet` which is true for dishes with `calories < 500`. 

```
=> App\Models\Dish {#4635
     id: 4,
     kitchen_id: 4,
     category_id: 1,
     name: "Bife à Rolê",
     chef_name: "Dan",
     price: 121.95,
     calories: 383,
     in_stock: 0,
     produced_at: "2022-02-17",
     created_at: "2022-03-15 17:53:55",
     updated_at: "2022-03-15 17:53:55",
     +is_diet: true,
   }
```
I am able to query `Dish::where('in_stock', '=', false)->get();` because `in_stock` is a database field.

However, if I try to query by `is_diet`:

![CleanShot 2022-03-16 at 18 08 53](https://user-images.githubusercontent.com/79267265/158647702-756604f8-bd95-4234-bc4e-179000d89cd1.png)


________
⭐ Enjoying PowerGrid? Please consider Starring the repository!
📢 Share PowerGrid with your dev-community, friends and colleagues: Tweet, write a blog, record review video. 
👥 PowerGrid is open-source, entirely developed and maintained by the author and the contributors.

**Comment by gallomaf** [comment]
Thank You for answer! I will find another solution :-)
However Powergrid it's very useful :-)
