### ISSUE TITLE
Component not found

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#43]
Keep up the good work here. Saw that the whole themeing system is updated, nice!

I'm getting the following error.
View [components\frameworks\tailwind\table-base] not found.

I also did a complete reinstall but the error still exists.

**Comment by luanfreitasdev** [comment]
This problem is very strange
I did several installs from scratch and couldn't reproduce

This was the last one I just made, called normal ..

![image](https://user-images.githubusercontent.com/33601626/128861433-ef7497f7-fdc2-4c82-b358-2cfec7d1fee2.png)

change in **config/livewire-powergrid.php**

`'theme' => 'tailwind',`

to

`'theme' => \PowerComponents\LivewirePowerGrid\Themes\Tailwind::class,`

- php artisan optimize:clear


**let's debug**

on the line 187 - **vendor\power-components\livewire-powergrid\src\PowerGridComponent.php** place dd

private function renderView($data)
    {
        dd($this->powerGridTheme);
        return view($this->powerGridTheme->layout->table, [
            'data'  => $data,
            'theme' => $this->powerGridTheme,
            'table' => 'livewire-powergrid::components.table'
        ]);
    }

something like:
PowerComponents\LivewirePowerGrid\Themes\Tailwind {#375 ▼
  +name: "tailwind"
  +base: "livewire-powergrid::components\frameworks\"
  +table: PowerComponents\LivewirePowerGrid\Themes\Components\Table {#376 ▼
    +tableClass: "min-w-full divide-y divide-gray-300 border-b dark:bg-gray-600 border-gray-400 "
    +tableStyle: ""
    +theadClass: "bg-gray-200 dark:bg-gray-700"
    +theadStyle: ""
    +trClass: "border border-gray-200 dark:border-gray-400"
    +trStyle: ""
    +thClass: "px-2 pr-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider whitespace-nowrap dark:text-gray-300"
    +thStyle: ""
    +tbodyClass: "text-gray-800"
    +tbodyStyle: ""
    +trBodyClass: "border border-gray-200 dark:border-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
    +trBodyStyle: ""
    +tdBodyClass: "px-3 py-2 whitespace-nowrap dark:text-gray-200"
    +tdBodyStyle: ""
  }
  +checkbox: PowerComponents\LivewirePowerGrid\Themes\Components\Checkbox {#383 ▶}
  +layout: PowerComponents\LivewirePowerGrid\Themes\Components\Layout {#363 ▶}
  +actions: PowerComponents\LivewirePowerGrid\Themes\Components\Actions {#373 ▶}
  +editable: PowerComponents\LivewirePowerGrid\Themes\Components\Editable {#382 ▶}
  +toggleable: PowerComponents\LivewirePowerGrid\Themes\Components\Toggleable {#364 ▶}
  +filterBoolean: PowerComponents\LivewirePowerGrid\Themes\Components\FilterBoolean {#386 ▶}
  +filterSelect: PowerComponents\LivewirePowerGrid\Themes\Components\FilterSelect {#390 ▶}
  +filterDatePicker: PowerComponents\LivewirePowerGrid\Themes\Components\FilterDatePicker {#387 ▶}
  +filterMultiSelect: PowerComponents\LivewirePowerGrid\Themes\Components\FilterMultiSelect {#388 ▶}
  +filterNumber: PowerComponents\LivewirePowerGrid\Themes\Components\FilterNumber {#389 ▶}
  +filterInputText: PowerComponents\LivewirePowerGrid\Themes\Components\FilterInputText {#391 ▶}
  +footer: PowerComponents\LivewirePowerGrid\Themes\Components\Footer {#378 ▶}
  +cols: PowerComponents\LivewirePowerGrid\Themes\Components\Cols {#379 ▶}
}

**Comment by edwinheij** [comment]
This is what is gave me:

```php
PowerComponents\LivewirePowerGrid\Themes\Tailwind {#375 ▼
  +name: "tailwind"
  +base: "livewire-powergrid::components\frameworks\"
  +table: PowerComponents\LivewirePowerGrid\Themes\Components\Table {#376 ▶}
  +checkbox: PowerComponents\LivewirePowerGrid\Themes\Components\Checkbox {#374 ▶}
  +layout: PowerComponents\LivewirePowerGrid\Themes\Components\Layout {#383 ▶}
  +actions: PowerComponents\LivewirePowerGrid\Themes\Components\Actions {#365 ▶}
  +editable: PowerComponents\LivewirePowerGrid\Themes\Components\Editable {#380 ▶}
  +toggleable: PowerComponents\LivewirePowerGrid\Themes\Components\Toggleable {#364 ▶}
  +filterBoolean: PowerComponents\LivewirePowerGrid\Themes\Components\FilterBoolean {#384 ▶}
  +filterSelect: PowerComponents\LivewirePowerGrid\Themes\Components\FilterSelect {#390 ▶}
  +filterDatePicker: PowerComponents\LivewirePowerGrid\Themes\Components\FilterDatePicker {#387 ▶}
  +filterMultiSelect: PowerComponents\LivewirePowerGrid\Themes\Components\FilterMultiSelect {#388 ▶}
  +filterNumber: PowerComponents\LivewirePowerGrid\Themes\Components\FilterNumber {#389 ▶}
  +filterInputText: PowerComponents\LivewirePowerGrid\Themes\Components\FilterInputText {#391 ▶}
  +footer: PowerComponents\LivewirePowerGrid\Themes\Components\Footer {#378 ▶}
  +cols: PowerComponents\LivewirePowerGrid\Themes\Components\Cols {#379 ▶}
}
```

**Comment by edwinheij** [comment]
Here 's the complete trace: https://flareapp.io/share/67O9eokm

**Comment by luanfreitasdev** [comment]
opening the layout is like this?

![image](https://user-images.githubusercontent.com/33601626/128868033-1af6a8aa-aa6b-4e0e-8e4a-06766c6dfd3d.png)

Looks like he doesn't understand the directory: livewire-powergrid::

**Comment by luanfreitasdev** [comment]
I don't know if there is, but did you install the package from scratch or all the dependencies of composer?

**Comment by luanfreitasdev** [comment]
Hello, I was forced to go back to the previous version.. I will investigate this problem better and i will upload a version with the new features that were present in the new version with the exception of the theme

**Comment by thetwopct** [comment]
Also seeing this, went back a few versions to experiment

1.1.5 - Fine
1.1.6 - Other Error (Method App\Http\Livewire\Staff::relationSearch does not exist)
1.1.7 - Fine
1.2.0 - View [components\frameworks\tailwind\table-base] not found
1.2.1 - View [components\frameworks\tailwind\table-base] not found
